apiVersion: v1
kind: Pod
metadata:
  name: ready-test
  labels:
    app: ready-app
spec:
  containers:
  - name: web
    image: nginx
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready-flag
      initialDelaySeconds: 2
      periodSeconds: 3